convert Microsoft.AVS 2023-03-01 to TypeSpec
cataggar/azure-rest-api-specs pull request #5
Opened 2023-10-18 01:05 UTC by cataggar

2023-10-23 20:32 UTC, markcowl requested changes
A small bit of remodeling would vastly simplify this spec, simply by using child resources and singleton resources, and by using the existing checkNamevailability operation templates

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @doc("Return trial status for subscription by region")
You will likely want to use either the checkGlobal or checkLocal name availability operation templates: https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/operations.tsp#L435-L471

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface Clusters {
You should just add Cluster as a child resource, by setting `@parentResource` for cluster, as described here: https://azure.github.io/typespec-azure/docs/getstarted/azure-resource-manager/step03

Then you can just use the standard operation templates.

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface Datastores {
same comment as above, DataStore should just be a child resource of Cluster

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface HcxEnterpriseSites {
hexEnterpriseSItes should be a child resource of privateClouds, as above

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface Authorizations {
model as a child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface GlobalReachConnections {
model as a chile resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface WorkloadNetworks {
model as a child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/workloadNetworks/default/dhcpConfigurations")
workloadNetworks should be modeld as a singleton resource: https://azure.github.io/typespec-azure/docs/howtos/ARM/resource-type#singleton-resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/workloadNetworks/default/dhcpConfigurations")
And dhcpConfiguration should be a child of this resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/workloadNetworks/default/gateways/{gatewayId}")
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/workloadNetworks/default/portMirroringProfiles/{portMirroringId}"
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  listVMGroups is Azure.Core.Foundations.Operation<
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  getVirtualMachine is Azure.Core.Foundations.Operation<
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  listDnsServices is Azure.Core.Foundations.Operation<
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  listDnsZones is Azure.Core.Foundations.Operation<
child

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  listPublicIPs is Azure.Core.Foundations.Operation<
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface CloudLinks {
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface Addons {
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +interface VirtualMachines {
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/clusters/{clusterName}/placementPolicies/{placementPolicyName}")
child resource

2023-10-23 20:32 UTC, markcowl commented on specification/vmware/Microsoft.AVS/routes.tsp
> +  @route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/clusters/{clusterName}/placementPolicies/{placementPolicyName}")
In geenral, you should never have `@route` in an ARM typespec.  If your resources are modeled as parent/children, you should be able to use the standard operation templates

2023-10-27 21:34 UTC, cataggar commented
Replaced by https://github.com/Azure/azure-rest-api-specs-pr/pull/15631

2023-10-27 21:34 UTC, closed without merging